replicaCount: 2

namespace: website-slide

image:
  repository: riqimaruq/website-slide
  tag: "4"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: []
