apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-slide
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: website-slide
  template:
    metadata:
      labels:
        app: website-slide
    spec:
      containers:
        - name: website-klinik
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
