apiVersion: v1
kind: Service
metadata:
  name: website-slide
spec:
  selector:
    app: website-slide
  ports:
  - port: 80
    targetPort: 80
  type: {{ .Values.service.type | default "ClusterIP" }}
